### ISSUE TITLE
99-killX.conf overrides my keyboard settings

### ISSUE THREAD

**Issue by otto-gebb** [arcolinux/arcolinux-system-config#2]
I have a file /etc/X11/xorg.conf.d/00-keyboard.conf with the following contents:
```
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,ru"
        Option "XkbModel" "pc105"
        Option "XkbVariant" "os_winkeys"
        Option "XkbOptions" "grp:caps_toggle,grp_led:scroll"
EndSection
```

Which sets CapsLock as the layout switch key.

The file 99-killX.conf breaks my desired setting by overriding it:
```
...
Option         "XkbOptions" "terminate:ctrl_alt_bksp"
```

As a workaround, I have to delete the 99-killX.conf after I update packages.

Is there a better way to deal with this? Or maybe a fix possible?

**Comment by arcolinuxz** [comment]
I would delete it and replace it with your keybinding.

These things I put in my arcolinux-nemesis scripts.
https://github.com/erikdubois/arcolinux-nemesis

You will see me removing stuff from all kinds of Arch based distros and take control over the files.
